kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: central-station-dev
  uid: 4ed0c814-844f-4277-9cd5-2ecb2d3206e7
  resourceVersion: "21751"
  creationTimestamp: "2021-09-20T01:19:31Z"
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  ownerReferences:
    - apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      name: regcred
      uid: 1cb88c6a-1017-4368-9d4a-f6b5bc2410a0
      controller: true
  managedFields:
    - manager: controller
      operation: Update
      apiVersion: v1
      time: "2021-09-20T01:19:31Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:.dockerconfigjson": {}
        "f:metadata":
          "f:annotations":
            .: {}
            "f:sealedsecrets.bitnami.com/cluster-wide": {}
          "f:ownerReferences":
            .: {}
            'k:{"uid":"1cb88c6a-1017-4368-9d4a-f6b5bc2410a0"}':
              .: {}
              "f:apiVersion": {}
              "f:controller": {}
              "f:kind": {}
              "f:name": {}
              "f:uid": {}
        "f:type": {}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MSI6eyJ1c2VybmFtZSI6ImRyZXdidXJyIiwicGFzc3dvcmQiOiJjYzI1ZGZjMy01ZmQ2LTRjNjUtOWQ1Mi0zODA5ZTA1NGQ4ZTgiLCJlbWFpbCI6ImRyZXdidXJyOUBnbWFpbC5jb20iLCJhdXRoIjoiWkhKbGQySjFjbkk2WTJNeU5XUm1Zek10Tldaa05pMDBZelkxTFRsa05USXRNemd3T1dVd05UUmtPR1U0In19fQ==
type: kubernetes.io/dockerconfigjson
