---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  template:
    spec:
      containers:
        - name: centralstation-bot
          image: drewburr/centralstation-bot:1.1.4
