---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: central-station-prd
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: drewburr/centralstation-bot:v1.0.1
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
      imagePullSecrets:
        - name: regcred
