---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  template:
    spec:
      containers:
        - name: discord-bot
          image: drewburr/centralstation-bot:master
          imagePullPolicy: Always
