---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralstation-bot
  template:
    metadata:
      labels:
        app: centralstation-bot
    spec:
      containers:
        - name: centralstation-bot
          image: drewburr/centralstation-bot:v0.0.0  # Version must be given in overlay
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: regcred
