apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    config.json: AgAtSAI+IRzSFKm9QqnwVhrFNAZrHmFCY+/Q1AsMErlUzKEpLBoZG1FbTM46+LOOnMpamM/4jkt4v6eYoXKJ9ew/5p0Sb7p6qksXfNhRPyEXiyH2ACfX7mXrl3wqNOEE8wxhvNtsRJRZkFUqAYWkBGPnzh5oEL7n0d9j/iiyIhwUYnBlpFhlV+b054aGvQz0YojjfmwlazRyW0SuPW6WIxmVvseFwTU10EAu2xy87p2UvbQrjBIipUIO+mXWRjc1xQFIxV1w7beTxLKQe+K5oDC3w9jq7QzT4w9WHL/0SGaIPQQGu7zI3tBIg9hGUs6dYtQcGpF683vT/Rf9iLDaXJPwKXho76IriUSlrSzi9Ry0tF6URUS2xF3ZFs11bglH/Jj5f1BE+nqGAN9GPsh30cj/UERm3nW8i456k8pcWx5hey8aTNmKEAKhtTv0TJD0xLMBjl856bDzzgL5s8UpkQPOZXR1iqSLzR+P1BVH7f3gdOfyi1/G9TwEfogUAxJA2POgcjVGonJku4nzCTyODuSirkhrbKNLOXLg5ZtomlehiCinlkDesI+JMHUhLdC3r7IbZRQR0nyCOw1WzkqZGeX1gMnrolMDVLwWK0ZmfempBVHFeBMrHT0YybavpYxq0zdUy3cGpt2voBCsaZQCimPxSHZtxCpgITWLv+rS17Du4ZM+TPzoWfKgVidi5+90pfFgBYG2h1+QYem20OKBzFPV6n0JYutcqyZb6Ky83YTgbIP8a0OS0kNojak+pf5azgS0VeBM4Yoem1vC4WYyiXfR/VC3m9kYO21hwh3inayyD+hi6fRPU/O6a/KVg6NqMkbbx/2G8nweZrDcThUHLSs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred

