apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mum-discord-bot
  namespace: mum-discord-bot
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/traefik
    repoURL: git@github.com:drewburr-labs/mum-discord-bot.git
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
