apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mum-discord-bot
  namespace: argocd
spec:
  destination:
    namespace: mum-discord-bot
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/chart
    repoURL: git@github.com:drewburr-labs/mum-discord-bot.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
